customhost = "database-2.crv9tiqtgg6m.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "fongxinyi-employee"
customregion = "us-east-1"
